# Before starting the inference, we need to preprocess the input data.
# Assuming our input data is of shape [h, w, c], the following parameters are its preprocessing parameters.
preprocess:
  # Resize the image to [1, 224, 224].
  - Resize:
      width: 224
      height: 224
  # Perform color channel transformation, converting RGB colors to BGR.
  - BGRToRGB:
  # Perform normalization operation.
  - Normalize:
      mean: &normalize_mean [ 0.485, 0.456, 0.406 ]
      std: &normalize_std [ 0.229, 0.224, 0.225 ]
  # The input to the ONNX model is in NCHW format, and we need to change the memory layout of the data from NHWC to NCHW.
  - HWCToCHW:

# After preprocessing, we obtain an input vector of [1, 3, 224, 224], and now we need to perform inference.
# The following parameters are the configuration settings for the RKNN backend:
rknn_export:
  - Config:
      mean_values: *normalize_mean
      std_values: *normalize_std
      target_platform: "RK3568"
#      target_platform: "RK3588"
  - LoadONNX:
      inputs: ["inputs"]
      input_size_list: [[1,3,224,224]]
      input_initial_val: null
      outputs: null
  - Build:
      do_quantization: false
      dataset: null
      rknn_batch_size: null


# After the inference, we obtain an output vector of [1, 1000], and we need to perform post-processing on the vector.
# The following parameters are for post-processing.
postprocess:
  # If the Softmax operator is missing from your model's output, the top K elements may not represent confidence.
  # You also need to apply the Softmax operation to the top K elements.
  - Softmax: false