# Before starting the inference, we need to preprocess the input data.
# Assuming our input data is of shape [h, w, c], the following parameters are its preprocessing parameters.
preprocess:
  # Resize the image to [1, 224, 224].
  - LetterBox:
      width: 640
      height: 640
      scalar: [ 114,114,114 ]
  # Perform color channel transformation, converting RGB colors to BGR.
  - BGRToRGB:
  # Perform normalization operation.
  - Normalize:
      mean: [ 0.5, 0.5, 0.5 ]
      std: [ 0.5, 0.5, 0.5 ]
  # The input to the ONNX model is in NCHW format, and we need to change the memory layout of the data from NHWC to NCHW.
  - HWCToCHW:

postprocess:
  - landmark_num: 5